spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.yibao.jwtdemo.entity
  mapper-locations: classpath:com/yibao/mapper/*.xml

